server:
  port: 9006
spring:
  application:
    name: tensquare-recruit #指定服务名
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  data:
    mongodb:
      host: 192.168.39.128
      database: recruitdb
  redis:
      host: 192.168.39.128
logging:
  config: classpath:config/logback/logback-dev.xml
  level:
    com.tensquare.base.dao: DEBUG

mongodb:
  spitdb:
    database01: spit