server:
  port: 8010
spring:
  application:
    name: tensquare-asset #指定服务名
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.39.128:3306/tensquare_asset?characterEncoding=utf-8
    username: root
    password: 123456

logging:
  config: classpath:config/logback/logback-dev.xml
  level:
    com.tensquare.base.dao: DEBUG

    #mybatis配置
mybatis:
    #typeAliasesPackage: com.tensquare.asset.pojo
    mapperLocations: classpath:mapper/*.xml
    #configLocation: classpath:/mybatis-config.xml
es:
  url: 192.168.39.128:9200
  userName:
  password: